name: Trigger SEI Repo Update

on:
  push:
    branches:
      - main

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SEI pipeline
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.GH_SECRET }}" \
               https://api.github.com/repos/EWinterhalter/test/dispatches \
               -d '{"event_type":"update_submodules"}'
