name: trigger

on:
  push:
    branches:
      - main

jobs:
  update-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this service
        uses: actions/checkout@v3

      - name: Checkout main 
        run: |
          git config --global user.name "winterhalter"
          git config --global user.email "winterhalter@github.com"
          git clone --recurse-submodules https://x-access-token:${{ secrets.GH_SECRET }}@github.com/EWinterhalter/test
          cd test
          git submodule update --remote --merge
          git commit -am "update submodules from $GITHUB_REPOSITORY" || true
          git push
